<?php
if (!N2Base::getApplication('smartslider')->storage->get('tutorial', 'free')) {

    N2Html::banner(array(
        'id'          => 'n2-ss-tutorial-free',
        'image'       => '$ss$/admin/images/free/gettingstarted.png',
        'imageLink'   => 'https://smartslider3.com/videos/freetutorial',
        'title'       => n2_('Learn Smart Slider 3'),
        'description' => n2_('We\'ve created a simple tutorial video to guide you through the basic steps of making your first slider. Good luck with the sliders!'),
        'buttons'     => array(
            '<a href="https://smartslider3.com/videos/freetutorial" class="n2-button n2-button-normal n2-button-green n2-button-l n2-h4 n2-b n2-uc n2-radius-s" target="_blank">' . n2_('Watch now') . '</a>',
            '<a onclick="N2Classes.AjaxHelper.ajax({url: N2Classes.AjaxHelper.makeAjaxUrl(\'' . $appType->router->createAjaxUrl(array('settings/hideTutorialFree')) . '\')});N2Classes.$(\'#n2-ss-tutorial-free\').remove(); return false;" href="#" class="n2-button n2-button-normal n2-button-grey n2-button-l n2-h4 n2-b n2-uc n2-radius-s" target="_blank">' . n2_('Close') . '</a>'
        )
    ));
};
